### ISSUE TITLE
!If seems to break rule E3002 for lists

### ISSUE THREAD

**Issue by michaelwittig** [awslabs/cfn-python-lint#140]
`!If` seems to break the type checker for lists. It seems to work with other types like boolean, strings, and `!Ref 'AWS::NoValue'`.

I get the following findings using v0.3.0:
```
E3002 Property AttributeDefinitions should be of type List for resource Table

E3002 Property KeySchema should be of type List for resource Table
```

For this template: 
```
Conditions:
  HasSortKey: !Not [!Equals [!Ref SortKeyName, '']]
  HasTableName: !Not [!Equals [!Ref TableName, '']]
  HasAwsManagedEncryption: !Equals [!Ref Encryption, aws]
Resources:
  Table:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !If [HasTableName, !Ref TableName, !Ref 'AWS::NoValue']
      AttributeDefinitions: !If
      - HasSortKey
      - - AttributeName: !Ref PartitionKeyName
          AttributeType: !Ref PartitionKeyType
        - AttributeName: !Ref SortKeyName
          AttributeType: !Ref SortKeyType
      - - AttributeName: !Ref PartitionKeyName
          AttributeType: !Ref PartitionKeyType
      KeySchema: !If
      - HasSortKey
      - - AttributeName: !Ref PartitionKeyName
          KeyType: HASH
        - AttributeName: !Ref SortKeyName
          KeyType: RANGE
      - - AttributeName: !Ref PartitionKeyName
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref MinReadCapacityUnits
        WriteCapacityUnits: !Ref MinWriteCapacityUnits
      SSESpecification:
        SSEEnabled: !If [HasAwsManagedEncryption, true, false]
```
