### ISSUE TITLE
Missing filename in error output

### ISSUE THREAD

**Issue by ashemedai** [awslabs/cfn-python-lint#142]
Using cfn-lint 0.3.0 I was trying to fix up linting on vim.

At some point while testing the linting I deleted a three W3010 warnings from this file (explicit mentions of Properties/AvailabilityZones under an RDSCluster node) and this caused cfn-lint to output the follow from the lint invocation: `:159:25:159:26:E0000:Null value at line 158 column 24`. As you can see, the filename is missing.

So it boils down to:

```yaml
RDSCluster:
  Type: "AWS::RDS::DBCluster"
  Properties:
    AvailabilityZones:
    BackupRetentionPeriod: 35
```

So in essence if a sequence of scalars is empty it will return this linting line, which misses the filename.

Also tested this with a `Resources/AutoScalingGroup/Properties/VPCZoneIdentifier` by removing all its scalars.
