### ISSUE TITLE
Incorrectly reporting issue with DynamoDB table Read and Write Capacity units

### ISSUE THREAD

**Issue by reidca** [awslabs/cfn-python-lint#147]
```
E3002 Property Resources/ConfigTable/Properties/ProvisionedThroughput/ReadCapacityUnits should be of type Integer
cloudformation/ec2/management/templates/instance-scheduler.yaml:945:9

```
```
E3002 Property Resources/ConfigTable/Properties/ProvisionedThroughput/WriteCapacityUnits should be of type Integer
cloudformation/ec2/management/templates/instance-scheduler.yaml:946:9
```

Resource is:

```
ConfigTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: type
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: type
          KeyType: HASH
        - AttributeName: name
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
```
