### ISSUE TITLE
Support SAM Globals when validating Functions

### ISSUE THREAD

**Issue by sbol-coolblue** [awslabs/cfn-python-lint#157]
I am getting E2531 (You must specify a valid value for runtime) in a SAM template. My Functions do have a Runtime specified, however, this is done via the [Globals](https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst) section. It seems that the parser currently does not yet take this section into account when validating this value (and possibly others?).

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs8.10

Resources:
  ## Snipped Gateway definition ##
  MyExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: example.handler
      FunctionName: example-function
      ## No Runtime defined here, is inherited from the Global:Function:Runtime section"
```

Output: `E2531 You must specify a valid value for runtime at nodejs8.10
template.yaml:<row>:<col>`
