### ISSUE TITLE
Nested mappings raise an error

### ISSUE THREAD

**Issue by alexjurkiewicz** [awslabs/cfn-python-lint#165]
```cfn-lint 0.3.1```

We use nested maps in our templates:

```yaml
Mappings:
  RegionAccountToAZ:
    ap-northeast-1:
      0123456789:
        - ap-northeast-1a
        - ap-northeast-1c
        - none
      9876543210:
        - ap-northeast-1a
        - ap-northeast-1b
        - ap-northeast-1c
```

We'd access this data using a construction like `!FindInMap [RegionAccountToAZ, !Ref 'AWS::Region', !Ref 'AWS::AccountId']`. However cfn-lint says:

```
E7001 Mapping RegionAccountToAZ has invalid property at 9876543210
test.cfn.yaml:3:5

E7001 Mapping RegionAccountToAZ has invalid property at 0123456789
test.cfn.yaml:4:7
```
