### ISSUE TITLE
Feature: Warning on substitions without !Sub

### ISSUE THREAD

**Issue by fatbasstard** [awslabs/cfn-python-lint#186]
*cfn-lint version: 0.3.2*

It's pretty annoying if you add a substition and forget the `!Sub`:
```
          - Effect: "Allow"
            Action:
              - "s3:ReplicateObject"
              - "s3:ReplicateDelete"
            Resource:
              - "arn:aws:s3:::mycompany-${Environment}-mybucketname/*"
```

I'm not 100% sure if a `${value}` always must be a substitution, since Cfn accepts this as valid string. But this could be a valid rule to give you a warning about this. Either you're missing the `!Sub` or you picked a real annoying string to be used...
