### ISSUE TITLE
AWS::RDS::OptionGroup OptionSettings spec vs docs

### ISSUE THREAD

**Issue by mattcanty** [awslabs/cfn-python-lint#188]
cfn-lint version: `1.5.1`

Lint failing due to spec discrepancy. CloudFormation successfully deploys.

`E3002 Expecting an object at Resources/SqlServerOptionGroup/Properties/OptionConfigurations/0/OptionSettings`

## Spec - [link](https://d3teyb21fexa9r.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json)
```
"AWS::RDS::OptionGroup.OptionConfiguration": {
  "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-optiongroup-optionconfigurations.html",
  "Properties": {
    "DBSecurityGroupMemberships": {REDACTED},
    "OptionName": {REDACTED},
    "OptionSettings": {
    "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-optiongroup-optionconfigurations.html#cfn-rds-optiongroup-optionconfigurations-optionsettings",
    "Required": false,
    "Type": "OptionSetting", <-- SHOULD BE LIST
    "UpdateType": "Mutable"
  },
  "OptionVersion": {REDACTED},
  "Port": {REDACTED},
  "VpcSecurityGroupMemberships": {REDACTED}
  }
},
```
## Doc - [link](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-optiongroup-optionconfigurations.html#cfn-rds-optiongroup-optionconfigurations-optionsettings)
![image](https://user-images.githubusercontent.com/2089581/42277606-d25f99c2-7f8f-11e8-871d-600e3a72dd03.png)
## Sample
```
SqlServerOptionGroup:
  Type: AWS::RDS::OptionGroup
  Properties:
    EngineName: !Ref EngineName
    MajorEngineVersion: !Ref MajorEngineVersion
    OptionGroupDescription: rds-sql-optiongroup
    OptionConfigurations:
      - OptionName: SQLSERVER_BACKUP_RESTORE
        OptionSettings:
          - Name: IAM_ROLE_ARN
            Value: !GetAtt SqlServerBackupRestoreRole.Arn
```

**Comment by fatbasstard** [comment]
Hi @mattcanty,

There is a bug in the Spec files, this is address at the AWS teams already by @cmmeyer. See Issue: https://github.com/awslabs/cfn-python-lint/issues/14

If this is blocking, you can work around it using the `override-spec` feature. That's some manually work but does the trick if really needed.

**Comment by mattcanty** [comment]
I went with 
```
cfn-lint:
    config:
      ignore_checks:
        - E3002 
```
until the issue is resolved, this is OK with us for now.
