### ISSUE TITLE
E1024 should allow Fn::ImportValue

### ISSUE THREAD

**Issue by michaelwittig** [awslabs/cfn-python-lint#199]
cfn-lint version: 0.3.3

The following template:

```
---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SubnetIndex:
    Description: 'Index of the subnet'
    Type: Number
    MinValue: 0
    MaxValue: 5
  SubnetCount:
    Description: 'To slice the IP address ranges you need to specify how many subnets you want to create in the VPC'
    Type: Number
    MinValue: 1
    MaxValue: 6
Resources:
  Subnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: !Select [!Ref SubnetIndex, !Cidr [{'Fn::ImportValue': 'vpc-CidrBlock'}, !Ref SubnetCount, 12]]
      VpcId: 'vpc-123456'
```

Produces the following exceptions and findings:

```
# not sure about this
E0002 Unknown exception while processing rule E1017: too many values to unpack
bug.yml:1:1

# looks like Cidr also supports Fn::ImportValue (at leats the template works)
E1024 Cidr ipBlock should be Cidr Range, Ref, or Select for Resources/Subnet/Properties/CidrBlock/Fn::Select/1/Fn::Cidr/0
bug.yml:18:7

# not quiet sure about that, 12 should be a int?
E1024 Cidr sizeMask should be a int for Resources/Subnet/Properties/CidrBlock/Fn::Select/1/Fn::Cidr/2
bug.yml:18:7
```
