### ISSUE TITLE
Support for VpcEndpointType and PrivateDnsEnabled attributes for AWS::EC2::VPCEndpoint

### ISSUE THREAD

**Issue by ravinaik1312** [awslabs/cfn-python-lint#219]
*cfn-lint version: (`0.3.5`)*

*Description of issue.*

Please provide as much information as possible:
* Template linting issues:
  * CloudFormationSample: 
```
AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC with multiple subnets, security groups, VPC endpoints, Nat Gateway, Virtual Private Gateway.'
Resources:
  VPCEndpointCloudWatchLogs:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: "vpc-ooo11"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.logs"
      VpcEndpointType: Interface
      PrivateDnsEnabled: True
      SubnetIds:
        - "subnet-0001"
      SecurityGroupIds:
        - "sg-0001"

```
  * cfn-lint output:
```
 $ cfn-lint --version
cfn-lint 0.3.5
 $ cfn-lint cfn-bug.yaml
E3002 Invalid Property Resources/VPCEndpointCloudWatchLogs/Properties/VpcEndpointType
cfn-bug.yaml:9:7

E3002 Invalid Property Resources/VPCEndpointCloudWatchLogs/Properties/PrivateDnsEnabled
cfn-bug.yaml:10:7

rnaik@LMTC-RNAIK:~/Documents/DevSrcCode/gd-cloudformation (loadbalancer-updates) $
```

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html#cfn-ec2-vpcendpoint-vpcendpointtype
The `VpcEndpointType` and `PrivateDnsEnabled` seems like they were recently added looking at the release history, feel free to label this as a feature if you think so.
