### ISSUE TITLE
Using `Fn::Split` in `ManagedPolicyArns` as part of a `AWS::IAM::Role` results in incorrect E1018 error

### ISSUE THREAD

**Issue by ps-jay** [awslabs/cfn-python-lint#254]
*cfn-lint version: 0.4.2*

*Description of issue.*

Using `Fn::Split` in `ManagedPolicyArns` as part of a `AWS::IAM::Role` results in incorrect E1018 error.

e.g.
```
E1018 Split unsupported function for Resources/EnhancedMonitoringRole/Properties/ManagedPolicyArns/Fn::Split
```

However, I think this is incorrect, since I have been able to produce a working stack based off a template that has this snippet:

```
...<snip>...
Parameters:
  MandatoryPolicies:
    Description: Provide a list of policies that are mandatory on all roles
    Type: CommaDelimitedList
...<snip>...
Resources:
  EnhancedMonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns: !Split
        - ","
        - !Sub
          - "${PolicyList},arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
          - PolicyList: !Join [",", !Ref "MandatoryPolicies"]
```

I passed the parameter this string (well, this is a sanitised version of it anyway...):
```
arn:aws:iam::999912312399:policy/SecOpsRestrictionPolicy,arn:aws:iam::999912312399:policy/IAMRestrictionPolicy
``` 

If you point me in the right direction, I may be able to contribute a patch.
