### ISSUE TITLE
E3002 error on Cloudformation Custom Resource

### ISSUE THREAD

**Issue by vbarba** [awslabs/cfn-python-lint#289]
cfn-lint version: 0.5.0

I got a lint error with the following resource:
```
Resources:
  CoreLookup:
    Properties:
      ServiceToken: !GetAtt
        - LookupStackOutputs
        - Arn
      StackName: !Join
        - '-'
        - - Core
          - !Ref EnvName
    Type: 'AWS::CloudFormation::CustomResource'
```

Accordingly to the documentation is it possible to add more properties to the custom resources:
[https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cfn-customresource.html]

According to the documentation:

```   
"AWS::CloudFormation::CustomResource": {
      "AdditionalProperties": true,
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cfn-customresource.html",
      "Properties": {
        "ServiceToken": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cfn-customresource.html#cfn-customresource-servicetoken",
          "PrimitiveType": "String",
          "Required": true,
          "UpdateType": "Immutable"
        }
      }
```

So I think that the linter is ignoring the "AdditionalProperties" flag.
