### ISSUE TITLE
W6001 does not work with !Sub

### ISSUE THREAD

**Issue by hoegertn** [awslabs/cfn-python-lint#291]
*cfn-lint version: 0.5.1*

*Description of issue.*

Given the following template: 

```
  GitlabDomain:
    Description: The domain name of the Gitlab server
    Value: !Sub
    - 'gitlab.${zone}'
    - zone: !ImportValue infra-ZonePublic-Name
```

I get the warning W6001 but I am not using just the imported value but creating a new value based on it. This should not result in a warning.
