### ISSUE TITLE
Getting an "Invalid attribute" for ValidationMethod for a Certificate

### ISSUE THREAD

**Issue by chefren** [awslabs/cfn-python-lint#302]
*cfn-lint version: 0.5.2*

*Description of issue.*
Getting an error for a property defined in the docs

Please provide as much information as possible:
* Template linting issues:
Throws an error for a documented property: "E3001 Invalid resource attribute ValidationMethod for resource MyCert"
  * Please provide a CloudFormation sample that generated the issue.
```
Resources:
  MyCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Join [".", ["*", !Ref Domain]]
      ValidationMethod: DNS
```
  * If present, please add links to the (official) documentation for clarification.
ValidationMethod [doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-certificatemanager-certificate.html#cfn-certificatemanager-certificate-validationmethod)
