### ISSUE TITLE
Add a check that CloudWatch Events Rules have <= 5 targets

### ISSUE THREAD

**Issue by adamchainz** [awslabs/cfn-python-lint#306]
*cfn-lint version: (`cfn-lint --version`) 0.5.0* (but nothing changed since afaict)

*Description of issue.*

CloudWatch Events has a limit of 10 targets per Rule, but this isn't validated by `ValidateTemplate` or `cfn-lint`'s rules. Consequently one has to wait til deploy time to discover this error message:

> CREATE_FAILED: At most 10 targets allowed.

Failing template:

```yaml
Resources:
  MyCronRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 6 * * ? *)
      Targets:
      - Id: Job1
        Arn: arn:target
      - Id: Job2
        Arn: arn:target
      - Id: Job3
        Arn: arn:target
      - Id: Job4
        Arn: arn:target
      - Id: Job5
        Arn: arn:target
      - Id: Job6
        Arn: arn:target
      - Id: Job7
        Arn: arn:target
      - Id: Job8
        Arn: arn:target
      - Id: Job9
        Arn: arn:target
      - Id: Job10
        Arn: arn:target
      - Id: Job11
        Arn: arn:target
```
