### ISSUE TITLE
Fn::If first element needs to be a condition and cannot be a function

### ISSUE THREAD

**Issue by kddejong** [awslabs/cfn-python-lint#316]
*cfn-lint version: (`cfn-lint --version`)*
5.0.2
*Description of issue.*
Template validation error: Template error: Fn::If requires a list argument with the first element being a condition

Please provide as much information as possible:
```
Resources:
  myInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !If [ !Ref ConditionToUse, 'ami-1234567',  'ami-abcdefg']
```
