### ISSUE TITLE
Fn::Cidr should support Fn::GetAtt (E1024)

### ISSUE THREAD

**Issue by martijnvandongen** [awslabs/cfn-python-lint#320]
* cfn-lint 0.6.1
* I get the following error: 

```
E1024 Cidr ipBlock should be Cidr Range, Ref, or Select for Resources/MySubnet/Properties/CidrBlock/Fn::Select/1/Fn::Cidr/0/template.yml:123:7
```
```
Resources:
  MySubnet:
    Properties:
      CidrBlock: !Select
        - 0
        - !Cidr
          - !GetAtt 'MyVPC.CidrBlock'
          - 16
          - 8
```

Although the documentation doesn't mention the Fn::GetAtt in the list of supported functions, it is used in the CloudFormation examples on the same page. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-cidr.html
