### ISSUE TITLE
Catch duplicate resources

### ISSUE THREAD

**Issue by fatbasstard** [awslabs/cfn-python-lint#35]
Dictionaries in Python don't support duplicate keys. If a YAML/JSON contains duplicate keys, the last occurrence is "used". 

If somebody is copy/pasting a bit too enthusiastic in a big template, weird result will happen....  Change a resource, deploy it, nothing changes. Spand hours on debugging only to find out the Resource occorred 2 times in the template... Yes, experienced this.... Pretty annoying.

Example:

```
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  mySnsTopic:
    Type: AWS::SNS::Topic
    Parameters:
      TopicName: "unused-topic-name"
  myS3Bucket:
    Type: AWS::S3::Bucket
  mySnsTopic:
    Type: AWS::SNS::Topic
    Parameters:
      TopicName: "used-topic-name"
```

There will be 1 SNS topic deployed, the one with `used-topic-name`. In this case pretty clear, but in bigger templates this is not desirable.
