### ISSUE TITLE
E0002 while processing E2509

### ISSUE THREAD

**Issue by pitkley** [awslabs/cfn-python-lint#355]
```console
$ cfn-lint --version
cfn-lint 0.7.2
```

I'm receiving the following error:

```
E0002 Unknown exception while processing rule E2509: expected string or bytes-like object
temp.yaml:1:1
```

with the following minimal working example:

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub
      - '${Var}'
      - Var: content
```

Deploying the above template works, so CloudFormation is fine with this construct. Is this a (fixable) bug in cfn-lint?
