### ISSUE TITLE
cfn-lint failing on yaml nested sequences

### ISSUE THREAD

**Issue by chizou** [awslabs/cfn-python-lint#359]
*cfn-lint version: 0.7.2

`aws cloudformation validate-template` is confirming the template is correct. 
I get the following output:
```
E0002 Unknown exception while processing rule E2506: 'list' object has no attribute 'get'
./radiant-beam.yml:1:1

E0002 Unknown exception while processing rule E2520: unhashable type: 'dict'
./radiant-beam.yml:1:1

E0002 Unknown exception while processing rule E1027: unhashable type: 'dict'
./radiant-beam.yml:1:1

E3002 Expecting an object at Resources/ELBHttpSecurityGroup/Properties/SecurityGroupIngress/0
./radiant-beam.yml:5:7
```
For the template below:
```yaml
Resources:
  ELBHttpSecurityGroup:
    Properties:
      GroupDescription: Enable HTTP access
      SecurityGroupIngress:
        - - CidrIp: 1.2.3.4/16
            Description: CDIR1
            FromPort: '80'
            IpProtocol: tcp
            ToPort: '80'
          - CidrIp: 5.6.7.8/24
            Description: CIDR2
            FromPort: '80'
            IpProtocol: tcp
            ToPort: '80'
      VpcId: !ImportValue
        'ImportValue'
    Type: AWS::EC2::SecurityGroup
```
