### ISSUE TITLE
E1010 Invalid GetAtt error message could be better

### ISSUE THREAD

**Issue by alexjurkiewicz** [awslabs/cfn-python-lint#367]
*cfn-lint version: (`cfn-lint --version`)* 0.7.1

Code:
```yaml
  ElasticSearchHostname:
    Value:
      Fn::GetAtt: ElasticSearchDomain.DomainEndpoint
```

(I mixed short and long form)

Current:
```
E1010 Invalid GetAtt E.l.a.s.t.i.c.S.e.a.r.c.h.D.o.m.a.i.n...D.o.m.a.i.n.E.n.d.p.o.i.n.t for resource ElasticSearchHostname
cfn/x.cfn.yaml:342:7
```

Better:
```
E1010 GetAtt expects an array of length 2, not String for resource ElasticSearchHostname
```

(nb, this is also an error in an *output*, not *resource*, but I didn't even notice that until filing the bug report. I guess my eyes skip over everything except the line number)
