### ISSUE TITLE
Multiple 'str_node' object has no attribute 'items' errors with bad Outputs section

### ISSUE THREAD

**Issue by cmmeyer** [awslabs/cfn-python-lint#403]
*cfn-lint version: (`cfn-lint --version`)*
0.8.1

*Description of issue.*
Multiple 'str_node' object has no attribute 'items' errors with bad Outputs section:

```
E0002 Unknown exception while processing rule E6001: 'str_node' object has no attribute 'items'
rds-cluster-template.yml:1:1

E0002 Unknown exception while processing rule E6005: 'str_node' object has no attribute 'items'
rds-cluster-template.yml:1:1

E0002 Unknown exception while processing rule E6012: 'str_node' object has no attribute 'items'
rds-cluster-template.yml:1:1

E0002 Unknown exception while processing rule E6004: 'str_node' object has no attribute 'items'
rds-cluster-template.yml:1:1

E0002 Unknown exception while processing rule E6002: 'str_node' object has no attribute 'items'
rds-cluster-template.yml:1:1
```

I recognize this template makes no sense, but we should probably do a better job of cacthing the problem.

Template:

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "i-2395829568"
Outputs:
  PathToMasterStackFile
```
