### ISSUE TITLE
Complex Condition breaks Properties check (E3002)

### ISSUE THREAD

**Issue by fatbasstard** [awslabs/cfn-python-lint#41]
Properties check breaks on complex Conditions that return multiple sub-properties. Example:

```
AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
Parameters:
  EnableGeoBlocking:
    Type: String
Conditions:
  EnableGeoBlocking: !Equals [ !Ref EnableGeoBlocking, "true" ]
Resources:
  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Enabled: true
        Restrictions:
          GeoRestriction:
            !If
              - EnableGeoBlocking
              -
                RestrictionType: whitelist
                Locations:
                  - BE
                  - LU
                  - NL
              - RestrictionType: none
```

This returns an error on the `!If`:

```
E3002 Expecting an object at Resources/CloudFrontDistribution/Properties/DistributionConfig/Restrictions/GeoRestriction/Fn::If/2
template.yaml:15:11
```
