### ISSUE TITLE
Better initial errors for poorly formed YAML/JSON

### ISSUE THREAD

**Issue by cmmeyer** [awslabs/cfn-python-lint#417]
*cfn-lint version: (`cfn-lint --version`)*
0.8.2

*Description of issue.*
Some of the entry-point errors for really broken templates are very cryptic.  We should identify situations where it makes more sense to drop back to general YAML/JSON linting or a generic "JSON/YAML is unparseable" error.

Our error:
`E0000 Null value at line 10 column 37`

CloudFormation `aws cloudformation validate-template` error:
`An error occurred (ValidationError) when calling the ValidateTemplate operation: Template format error: [/Resources/PublicSubnetRouteTableAssociation1] resource definition is malformed`

We should be at least as good.

Template:

```yaml
Parameters:
  PublicRouteTable:
    Type: String
    Default: rt-123
  PublicSubnet01:
    Type: String
    Default: s-123456
Conditions:
  CreateAuxiliaryNetworks: !Equals [ !Ref PulicSubnet01, prod ]
Resources:
  PublicSubnetRouteTableAssociation1:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
    RouteTableId: {Ref: PublicRouteTable}
    SubnetId: {Ref: PublicSubnet01}

  AuxiliaryPublicSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateAuxiliaryNetworks
    Properties:
      RouteTableId: {Ref: PublicRouteTable}
      SubnetId: {Ref: PublicSubnet01}
```
