### ISSUE TITLE
E2507 error when using using policy statements for serverless functions

### ISSUE THREAD

**Issue by Dunedan** [awslabs/cfn-python-lint#423]
*cfn-lint version: 0.8.2* (and doesn't happen with earlier versions)

The template below produces the following error when processing it with `cfn-lint`:
```
E0002 Unknown exception while processing rule E2507: 'str' object has no attribute 'start_mark'
function_with_policy_templates.yaml:1:1
````

```yaml
AWSTemplateFormatVersion: '2010-09-09'

Transform: 'AWS::Serverless-2016-10-31'

Resources:
  Test:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ./
      Handler: hello.handler
      Runtime: python3.6
      Policies:
        - Statement:
          - Action: [ 'dynamodb:*' ]
            Effect: Allow
            Resource: '*'
```

That issue goes away when removing the `Transform: 'AWS::Serverless-2016-10-31'`, but that's of course no fix, as that would prevent transformation of the `AWS::Serverless::Function`.
