### ISSUE TITLE
Invalid FindInMap does not get picked up

### ISSUE THREAD

**Issue by hoshsadiq** [awslabs/cfn-python-lint#425]
Got the following mapping:
```
Mappings:
  CertificateMap:
    us-east-1:
      Arn: arn:aws:acm:us-east-1:<account>:certificate/<id>

Resources
  AppAlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      # ...
      Certificates:
        - CertificateArn:
            Fn::FindInMap: [CertificateMap, !Ref 'AWS::Region', id]
```

As you can see, `Fn::FindInMap` is referencing the `id` key instead of `Arn`. We should add a rule to fail in such a scenario.
