### ISSUE TITLE
E0002 Unknown exception while processing rule E2507: 'str' object has no attribute 'start_mark'

### ISSUE THREAD

**Issue by austinbyers** [awslabs/cfn-python-lint#430]
*cfn-lint version: 0.8.2*

## Error
When linting, the latest version of cfn-lint now breaks on IAM policies in Serverless templates
```
$ cfn-lint test.yml
E0002 Unknown exception while processing rule E2507: 'str' object has no attribute 'start_mark'
test.yml:1:1
```

This error does not happen if I roll back to `cfn-lint==0.8.1`

## Template
```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: test-python-function
      Handler: main.lambda_handler
      CodeUri: src/
      MemorySize: 128
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - 'lambda:InvokeFunction'
              Resource:
                - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*'
      Runtime: python3.6
      Timeout: 300
```
