### ISSUE TITLE
Missing key in AutoScalingGroup resource type

### ISSUE THREAD

**Issue by agamzn** [awslabs/cfn-python-lint#442]
*cfn-lint version: (`cfn-lint --version`)*

➜ cfn-lint --version
cfn-lint 0.7.4

*Description of issue.*

The current linting rules do not account for the `NotificationConfiguration` key within the `AWS::AutoScaling::AutoScalingGroup` resource type.

Please provide as much information as possible:

* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
(Only relevant parts shown)
```
  WorkloadAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      NotificationConfiguration:
        TopicARN: !Ref NotificationTopic
        NotificationTypes:
        - autoscaling:EC2_INSTANCE_LAUNCH
        - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
        - autoscaling:EC2_INSTANCE_TERMINATE
        - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
        - autoscaling:TEST_NOTIFICATION
```

  * If present, please add links to the (official) documentation for clarification.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-notificationconfigurations
