### ISSUE TITLE
Error: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by eschneider1271** [awslabs/cfn-python-lint#456]
*cfn-lint version: (`cfn-lint --version`)*
`cfn-lint 0.9.0`

NOTE: version 0.8.3 works fine, so the issue seems to have been introduced in this latest version. 

*Description of issue.*
```
$ cfn-lint test.yaml
2018-11-13 18:40:28,869 - cfnlint - ERROR - Tried to process rules on file test.yaml but got an error: 'NoneType' object is not iterable
```

Please provide as much information as possible:
* Template linting issues:

test.yaml:
```
---
AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - E0002

Parameters:
  NodeCount:
    Type: String
    AllowedPattern: '[1-7]'
    Default: 1
```

Thanks.
