### ISSUE TITLE
E2532 - StateMachine Json not parsing when using multi param !Sub

### ISSUE THREAD

**Issue by eaddingtonwhite** [awslabs/cfn-python-lint#475]
**cfn-lint version:**
```
$ cfn-lint --version
cfn-lint 0.9.1
```
**Description of issue:**
When using `!Sub` with 2 parameters as defined [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html) then cfn-lint chokes on the parameter being subbed in because technically this is not valid json. This is valid cloud formation though.
 
**Here is basic example showing issue:**
```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  TestParam:
    Type: String

Resources:

  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: TestStatemachine
      RoleArn: arn:aws:iam::123456789012:role/test-role
      DefinitionString:
        !Sub
      - |
        {
          "StartAt": "FlowChoice",
          "States": {
            "FlowChoice": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.sleep",
                  "StringEquals": "true",
                  "Next": "Sleep"
                },
                {
                  "Variable": "$.sleep",
                  "StringEquals": "false",
                  "Next": "Stop"
                }
              ],
              "Default": "Stop"
            },
            "Sleep": {
              "Type": "Wait",
              "Seconds": ${TestParam},   # <--- Not handled!
              "Next": "Stop"
            },
            "Stop": {
              "Type": "Succeed"
            }
          }
        }
      - {TestParam: !Ref TestParam}
```
