### ISSUE TITLE
RDS Properties

### ISSUE THREAD

**Issue by stabwah** [awslabs/cfn-python-lint#491]
cfn-lint version: 0.9.2

Missing properties for AWS RDS instances as described at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html

Example:
  E3002 Invalid Property Resources/AuroraInstance1/Properties/EnablePerformanceInsights
  E3002 Invalid Property Resources/AuroraInstance1/Properties/PerformanceInsightsRetentionPeriod

**Comment by kddejong** [comment]
@stabwah I may need to see more of your template.   Did you change the region you are testing against?  These attributes existed in our spec files starting in release v0.9.0.  You have v0.9.2 so you should have the most recent version.  One other option would be to run `cfn-lint --update-specs` which will re-download the specs.  
 We get the specs from here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html

```
---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  RdsInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      EnablePerformanceInsights: True
      PerformanceInsightsRetentionPeriod: 10
      DBInstanceClass: t2.micro
```
Results for this template.
```
✗ cfn-lint test.yaml
✗ echo $?
0
✗ cfn-lint --version
cfn-lint 0.9.2
```
