### ISSUE TITLE
Handle SSM parameters

### ISSUE THREAD

**Issue by hoegertn** [awslabs/cfn-python-lint#513]
The check E2505 fails when reading the CIDR from SSM using the following code:

```
  VpcCidr:
    Description: 'VPC CIDR Block'
    Type: AWS::SSM::Parameter::Value<String>
    Default: /Infra/VpcCidr
```

The message is misleading, too. It is about security groups and not cidr ranges.

https://github.com/awslabs/cfn-python-lint/blob/3b785df6b262b733bedcaa8c8de9a2c65ac161b8/src/cfnlint/rules/resources/ectwo/Vpc.py#L92
