### ISSUE TITLE
Invalid or Unsupported Type AWS::Lambda::LayerVersion

### ISSUE THREAD

**Issue by shawnsi** [awslabs/cfn-python-lint#551]
*cfn-lint version: 0.10.2*

*E3001 Invalid or unsupported Type AWS::Lambda::LayerVersion for resource*

This template yields a E3001 error:

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  FunctionDependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri:
        Bucket: not-a-real-bucket
        Key: not-a-real-key
      CompatibleRuntimes:
        - python3.6
```

For now I can workaround by ignoring E3001 but due to the lack of line level ignores this workaround is less than ideal.  Linting will no longer detect *any* invalid resource type with this workaround in place.

Thanks!
