### ISSUE TITLE
cfn-lint throwing E3002 instead of W3002 on Lambda::LayerVersion

### ISSUE THREAD

**Issue by RadicalDev** [awslabs/cfn-python-lint#608]
*cfn-lint version: `0.12.1`*

*Description of issue.*

cfn-lint is throwing `E3002 Expecting an object at Resources/LambdaLayerVersion/Properties/Content` when linting a template where a path is passed for a `AWS::Lambda::LayerVersion`'s `Content` similarly to how we would do that for a `AWS::Lambda::Function`'s `Code`. 

This is intended to work with the `aws cloudformation package` command which now supports `AWS::Lambda::LayerVersion`. 

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
```yaml
AWSTemplateFormatVersion: 2010-09-09

Resources:

  LambdaLayerVersion:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Description: A layer version which will contain static content
      CompatibleRuntimes:
        - python3.6
        - python3.7
      Content: ../static-content
```
  * If present, please add links to the (official) documentation for clarification.

    The documentation doesn't mention `aws cloudformation package` support for `AWS::Lambda::LayerVersion` yet, but support was added in aws-cli version [1.16.93](https://github.com/aws/aws-cli/blob/1.16.93/awscli/customizations/cloudformation/artifact_exporter.py#L373)

* Feature request:
  * Please provide argumentation about the missing feature. Context is key!

We're packaging static files in lambda layers and would like for cfn-lint to provide the expected behavior of throwing a warning like `W3002 This code may only work with `package` cli command as the property (Resources/LambdaLayerVersion/Properties/Content) is a string`
