### ISSUE TITLE
Spec Bug "AWS::Route53::HealthCheck" "AlarmIdentifier" (required) ?

### ISSUE THREAD

**Issue by fatbasstard** [awslabs/cfn-python-lint#623]
According to the documentation and the Specfiles the `AlarmIdentifier` of the
Route 53 HealthCheck HealthCheckConfig is optional. But I get the following error:

![image](https://user-images.githubusercontent.com/35613489/51989004-60e06300-24a6-11e9-99d7-89b5d05a907d.png)

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-healthcheckconfig.html#cfn-route53-healthcheck-healthcheckconfig-alarmidentifier
https://docs.aws.amazon.com/Route53/latest/APIReference/API_HealthCheckConfig.html

Used resource:
```
  Route53HealthCheck:
    Type: "AWS::Route53::HealthCheck"
    Properties:
      HealthCheckConfig:
        InsufficientDataHealthStatus: "Healthy" # Valid AllowedValue
        Type: "CLOUDWATCH_METRIC"
```

@cmmeyer Can you share some light on this?
