### ISSUE TITLE
Error when Fn::ImportValue is on the same line as attribute name

### ISSUE THREAD

**Issue by milancermak** [awslabs/cfn-python-lint#630]
*cfn-lint 0.13.1*

I'm getting a `E0000 mapping values are not allowed here` issue in the following template:
```yaml
---

AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Service:
    Type: String

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Image: 'Fn::ImportValue': !Sub '${Service}-ContainerURI'
```

However, if I put the `Fn::ImportValue` on a separate line, the linter is 👍 
```yaml
---

AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Service:
    Type: String

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Image:
            'Fn::ImportValue': !Sub '${Service}-ContainerURI'
```
Aren't both templates equivalent? 

To be honest, it's not such a big issue for me, I'm fine if you'll decide on WONTFIX. Just wanted to let you know.
