### ISSUE TITLE
Invalid Layers Property for AWS::Serverless::Function

### ISSUE THREAD

**Issue by tomislacker** [awslabs/cfn-python-lint#633]
#### Version
```sh
$ cfn-lint --version
cfn-lint 0.13.1
```

#### Description
```sh
$ cfn-lint mytemplate.yaml 
E0001 Resource with id [MyFunction] is invalid. property Layers not defined for resource of type AWS::Serverless::Function
mytemplate.yaml:1:1
```

* The `Layers` property is, in fact, defined
* The error line/column number is incorrect

#### Example Template

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample

Resources:
  FunctionDependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri:
        Bucket: not-a-real-bucket
        Key: not-a-real-key
      CompatibleRuntimes:
        - python3.6

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/
      Handler: index.handler
      Layers:
        - !Ref FunctionDependencyLayer
      Runtime: python3.6
      MemorySize: 128
      Timeout: 30
```

#### Support Documentation
The [AWS::Serverless::Function](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction) specification for has the `Layers` parameter and it's a list of strings:

> List of LayerVersion ARNs that should be used by this function. The order specified here is the order that they will be imported when running the Lambda function.

Additionally, the [AWS::Serverless::LayerVersion
](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlesslayerversion) specification indicates that it's return value is an ARN, so it should be appropriate:

> When the logical ID of this resource is provided to the Ref intrinsic function, it returns the resource ARN of the underlying Lambda LayerVersion.
