### ISSUE TITLE
Nested Sequence Error - "E3002 Expecting an object..."

### ISSUE THREAD

**Issue by andreimahu** [awslabs/cfn-python-lint#656]
*cfn-lint version: 0.14.0*

*Description of issue.*
The following structure throws: "E3002 Expecting an object at Resources/CodeBuildProject/Properties/Triggers/FilterGroups/0"

```
CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Triggers:
        Webhook: true
        FilterGroups:
        - - Type: EVENT
            Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED,PULL_REQUEST_REOPENED
          - Type: BASE_REF
            Pattern: ^refs/heads/master$
            ExcludeMatchedPattern: false
```

I have trimmed the unnecessary properties.
Details about the structure can be seen here: https://docs.aws.amazon.com/codebuild/latest/userguide/sample-github-pull-request.html#sample-github-pull-request-filter-webhook-events (scroll to the bottom)

**Comment by kddejong** [comment]
Looks like the CloudFormation spec is a little off here.  Looking a little deeper.

**Comment by kddejong** [comment]
Fixed with #658.  Waiting on the next release.  Looks like they created a simple type in the CloudFormation spec.  We hadn't built around this as it didn't exist before this use case.  We have a fix now and should have something released shortly.

**Comment by dpnova** [comment]
not 100% the same example, but I'm getting a similar error for a block like this:

```
  # Create a LoadBalancerListener and attach the TargetGroup and LoadBalancer
  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: 
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Protocol: HTTPS
      Port: 443
      Certificates: 
        - "{{resolve:secretsmanager:common:SecretString:SSL_ARN}}"
```


```
± cfn-lint infra/backend.yaml
E3002 Expecting an object at Resources/LoadBalancerListener/Properties/Certificates/0
infra/backend.yaml:414:11
````
