### ISSUE TITLE
Best way to handle parameters from nested stacks?

### ISSUE THREAD

**Issue by irvingpop** [awslabs/cfn-python-lint#66]
This project is awesome and super useful!

I can imagine the complexity of linting nested stacks is super high and wouldn't expect that, but how are folks handling situations where Outputs from nested stacks are being used?

For example, given this code:
```
            /etc/aws-signing-proxy.yml:
              content: !Sub |
                listen-address: 127.0.0.1
                port: 9200
                target: https://${ElasticsearchStack.Outputs.DomainEndpoint}
                region: ${AWS::Region}
```

always throws:
```
E1019 String parameter ElasticsearchStack.Outputs.DomainEndpoint not found in string for Resources/ServerLaunchConfig/Metadata/AWS::CloudFormation::Init/es_proxy_setup/files//etc/aws-signing-proxy.yml/content/Fn::Sub
```

I don't want to disable all E1019 checks because they're useful.  Would it maybe be right, for now, to exclude all parameters that have `/.Outputs./` in their name?
