### ISSUE TITLE
Unused Mapping Warning does not work with nested FindInMap

### ISSUE THREAD

**Issue by fatbasstard** [awslabs/cfn-python-lint#95]
Related to issue https://github.com/awslabs/cfn-python-lint/issues/57

When a nested FindInMap is used, it raises a warning on the mapping not used.

Example:

Resource part:
```
CidrBlock: !FindInMap [!FindInMap ["Environment", !Ref "Environment", "Subnets"], "eu-west-1a", "Management"]
```
Mapping:
```
Mappings:
  Environment:
    acceptance:
      Subnets: "AcceptanceSubnets"
    testing:
      Subnets: "TestingSubnets"
    production:
      Subnets: "ProductionSubnets"
  AcceptanceSubnets:
    eu-west-1a:
      Management: "XXX.XXX.XXX.XXX/XX"
...
```

This raises the warning: `W7001 - Mapping AcceptanceSubnets not used (line: 90)`
