### ISSUE TITLE
FindInMap in Conditions

### ISSUE THREAD

**Issue by kddejong** [awslabs/cfn-python-lint#99]
```
Conditions:
  cCreate:
    Fn::Equals:
    - !FindInMap [myMap, !Ref myInstance1, instance ]
    - true
Resources:
  myInstance1:
    Condition: cCreate
    Type: AWS::EC2::Instance
    Properties:
      ImageId: abc-1234567
```
should result in `Template validation error: Template format error: Unresolved dependencies [myInstance1]. Cannot reference resources in the Conditions block of the template`

New rule has alerts on any Ref in the Conditions block thats go to a Resource.
